buildscript {
    repositories {
        maven { url = "https://files.minecraftforge.net/maven" }
        maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
    }
    dependencies {
        classpath group: "net.minecraftforge.gradle", name: "ForgeGradle", version: "6.0.46", changing: true
        classpath group: "org.spongepowered", name: "mixingradle", version: "0.7-SNAPSHOT"
    }
}

plugins {
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

apply plugin: "net.minecraftforge.gradle"
apply plugin: "eclipse"
apply plugin: "maven-publish"
apply plugin: "org.spongepowered.mixin"


publishMods {
    changelog = "- Added config for emi hiding" +
            "- If you naively add From the Ground Up Charged Creepers as a natural spawn with a Forge Biome Modifier, it will automatically:" +
            "   - Spawn only on thunderstorms" +
            "   - Spawn only when when there are no charged creepers in a 200 block radius" +
            "   - This option must be enabled in the config and does nothing on its own. Modpack devs must add the charged creeper spawns themselves." +
            "- The From the Ground Up Charged Creeper's Spore Rocket attack will spawn a Savage and Ravage Spore Cloud." +
            "- Added an option, disabled by default, to make gingerbread men drop Windswept gingerbread cookies instead of gingerbread crumbs" +
            "- Removes the monster rarity added by Dungeon's Delight."
    type = STABLE
    file = jar.archiveFile
    modLoaders.add("forge")
    modLoaders.add("neoforge")
//    curseforge {
//        projectId = "993840"
//        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
//        minecraftVersions.add("1.20.1")
//        javaVersions.add(JavaVersion.VERSION_17)
//        clientRequired = true
//        serverRequired = true
//        requires("blueprint", "farmers-delight", "supplementaries", "quark")
//        optional("atmospheric", "ftgu-from-the-ground-up", "windswept", "alexs-caves", "biomes-o-plenty", "cave-delight", "clayworks", "create".
//            "dungeons-delight", "dye-depot", "environmental", "mowzies-mobs", "jadens-nether-expansion", "my-nethers-delight", "neapolitan", "oreganized",
//                "savage-and-ravage", "species", "windswept", "woodworks")
//    }
//    modrinth {
//        accessToken = providers.environmentVariable("MODRINTH_API_KEY")
//        projectId = "12345678"
//        minecraftVersions.add("1.20.1")
//
//        // You can use the shortened method if you only need to specify the slug
//        requires("blueprint", "farmers-delight", "supplementaries", "quark")
//        optional("atmospheric", "from-the-ground-up", "windswept", "alexs-caves", "biomes-o-plenty", "cave-delight", "clayworks", "create".
//                "dungeons_delight", "dye-depot", "environmental", "mowzies-mobs", "jadens-nether-expansion", "my-nethers-delight", "neapolitan", "oreganized",
//                "savage-and-ravage", "species", "windswept", "woodworks")
//    }
}

mixin {
    add sourceSets.main, "${project.modId}.refmap.json"
}

version = "${project.minecraft}-${project.modVersion}"
group = "com.dolt"
archivesBaseName = project.modId

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: "official", version: project.minecraft
    accessTransformer = file("src/main/resources/META-INF/accesstransformer.cfg")
    runs {
        client {
            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"
            arg "-mixin.config=" + project.modId + ".mixins.json"
            mods {
                dolt_mod_how {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"
            arg "-mixin.config=" + project.modId + ".mixins.json"
            mods {
                dolt_mod_how {
                    source sourceSets.main
                }
            }
        }
        data {
            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"
            property "blueprint.indev", "true"
            args "--mod", project.modId, "--all", "--output", file("src/generated/resources/"), "--existing", file("src/main/resources"),
                    "--existing-mod", "blueprint", "--existing-mod", "brewinandchewin", "--existing-mod", "doom_and_gloom", "--existing-mod", "dye_depot", "--existing-mod", "heart_crystals", "--existing-mod", "netherexp", "--existing-mod", "blasted_barrens", "--existing-mod", "alexscaves", "--existing-mod", "atmospheric", "--existing-mod", "quark"
            mods {
                dolt_mod_how {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft}-${project.forge}"
    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
    implementation fg.deobf("com.teamabnormals:blueprint:${project.minecraft}-${project.blueprint}")
    implementation fg.deobf("com.teamabnormals:boatload:${project.minecraft}-${project.boatload}")

    compileOnly fg.deobf("dev.emi:emi-forge:${emi_version}:api")
    runtimeOnly fg.deobf("dev.emi:emi-forge:${emi_version}")

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.0")) {
        jarJar.ranged(it, "[0.5.0,)")
    }

    compileOnly(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:0.3.2-beta.4"))
    implementation(jarJar("com.github.bawnorton.mixinsquared:mixinsquared-forge:0.3.2-beta.4")) {
        jarJar.ranged(it, "[0.3.2-beta.4,)")
    }

    implementation fg.deobf("curse.maven:farmers-delight-398521:${project.farmersDelight}")

    implementation fg.deobf("curse.maven:alexs-caves-924854:${project.alexCaves}")
    implementation fg.deobf("curse.maven:citadel-331936:${project.citadel}")

    implementation fg.deobf("maven.modrinth:supplementaries:${project.supplementaries}")
    implementation fg.deobf("maven.modrinth:moonlight:${project.moonlight}")
    implementation fg.deobf("maven.modrinth:species:${project.species}")
    implementation fg.deobf("maven.modrinth:amendments:${project.amendments}")
//    implementation fg.deobf("maven.modrinth:spawn-mod:${project.spawn}")
    implementation fg.deobf("maven.modrinth:abnormals-delight:${project.abnormalsdelight}")
    implementation fg.deobf("maven.modrinth:dye-depot:${project.dyeDepot}")
    implementation fg.deobf("curse.maven:zeta-968868:${project.zeta}")

    implementation fg.deobf("maven.modrinth:my-nethers-delight:${project.myNethersDelight}")
    implementation fg.deobf("curse.maven:quark-243121:${project.quark}")

    implementation fg.deobf("maven.modrinth:mowzies-mobs:${project.mowziesMobs}")
    implementation fg.deobf("maven.modrinth:blasted-barrens:${project.blastedBarrens}")
    implementation fg.deobf("maven.modrinth:clayworks:${project.clayworks}")
    implementation fg.deobf("maven.modrinth:woodworks:${project.woodworks}")

    implementation fg.deobf("maven.modrinth:oreganized:${project.oreganized}")
    implementation fg.deobf("maven.modrinth:doom-gloom:${project.doomGloom}")

    implementation fg.deobf("maven.modrinth:ferrite-core:${project.ferriteCore}")
    implementation fg.deobf("maven.modrinth:dungeons_delight:${project.dungeonsDelight}")
    implementation fg.deobf("maven.modrinth:runiclib:${project.runiclib}")
    implementation fg.deobf("maven.modrinth:from-the-ground-up:${project.ftgu}")
    implementation fg.deobf("maven.modrinth:caverns-and-chasms:${project.cavernsAndChasms}")


    compileOnly fg.deobf("mezz.jei:jei-${project.minecraft}-common-api:${project.jei}")
    compileOnly fg.deobf("mezz.jei:jei-${project.minecraft}-forge-api:${project.jei}")
    runtimeOnly fg.deobf("mezz.jei:jei-${project.minecraft}-forge:${project.jei}")


    implementation fg.deobf("maven.modrinth:gallery:${project.gallery}")
    implementation fg.deobf("maven.modrinth:savage-and-ravage:${project.savageandravage}")
    implementation fg.deobf("maven.modrinth:atmospheric:${project.atmospheric}")

    implementation fg.deobf("maven.modrinth:jadens-nether-expansion:${project.jne}")
    implementation fg.deobf("maven.modrinth:elysium-api:${project.elysium}")


    implementation fg.deobf("maven.modrinth:environmental:${project.environmental}")
    implementation fg.deobf("maven.modrinth:upgrade-aquatic:${project.upgradeAquatic}")

    compileOnly fg.deobf("maven.modrinth:etcetera:${project.etcetera}")

    implementation fg.deobf("maven.modrinth:neapolitan:${project.neapolitan}")
    implementation fg.deobf("maven.modrinth:atmospheric:${project.atmospheric}")
    implementation fg.deobf("maven.modrinth:heart_crystals:${project.heart_crystals}")
    implementation fg.deobf("maven.modrinth:brewin-and-chewin:${project.brewinAndChewin}")

    implementation fg.deobf("curse.maven:geckolib-388172:5675221")
}

repositories {
    mavenLocal()

    maven { url "https://maven.teamabnormals.com" }
    maven { url "https://dvs1.progwml6.com/files/maven/" }
    maven { url "https://maven.bawnorton.com/releases" }
    maven { url "https://modmaven.k-4u.nl" }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        forRepositories(fg.repository) // Only add this if you're using ForgeGradle, otherwise remove this line
        filter {
            includeGroup "maven.modrinth"
        }
    }

    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }

    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : project.modName,
                "Specification-Vendor"    : "Team Doltum",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.modName,
                "Implementation-Version"  : project.modVersion,
                "Implementation-Vendor"   : "Doltum",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs"            : project.modId + ".mixins.json"
        ])
    }
}


publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}