org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
gradle.cache.push=false

modName=Dolt Mod How
modId=dolt_mod_how
modVersion=2.4.1

minecraft=1.20.1
forge=47.3.1
boatload=5.0.1
blueprint=7.1.2

alexCaves=5848216
atmospheric=FLieTnyi
blastedBarrens=GUiITa5n
brewinAndChewin=9myDFPCD
cavernsAndChasms=6040957
citadel=5633260
clayworks=ZbSpUtwV
doomGloom=l8JYHm8w
dungeonsDelight=af67nAVt
emi=1.1.22+1.20.1
environmental=k7F41lm3
etcetera=uua8xPy8
farmersDelight=5051242
gallery=y24FMfgI
jei=15.20.0.106
mowziesMobs=my31qVfF
neapolitan=AC9UEwPQ
myNethersDelight=5673085
# 13.39
moonlight=Ntibd2fS
oreganized=vFdNU8EI
runiclib=ctmYY1Aj
species=xkMjveeZ
# 3.1.11
supplementaries=8fif4M3b
woodworks=236Amnif
zeta=5597406
quark=5594847
upgradeAquatic=zlrhxqCv
