org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
gradle.cache.push=false

modName=Dolt Mod How
modId=dolt_mod_how
modVersion=2.2.7

minecraft=1.20.1
forge=47.2.0
boatload=5.0.1
blueprint=7.1.2

alexCaves=5848216
atmospheric=FLieTnyi
blastedBarrens=GUiITa5n
cavernsAndChasms=6040957
citadel=5633260
environmental=k7F41lm3
etcetera=uua8xPy8
farmersDelight=5051242
gallery=y24FMfgI
jei=15.3.0.4
mowziesMobs=my31qVfF
neapolitan=AC9UEwPQ
myNethersDelight=5673085
moonlight=5995640
oreganized=5890510
supplementaries=5948497
zeta=5597406
quark=5594847
upgradeAquatic=zlrhxqCv
