org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
gradle.cache.push=false

modName=Dolt Mod How
modId=dolt_mod_how
modVersion=2.2.1

minecraft=1.20.1
forge=47.2.0
boatload=5.0.1
blueprint=7.1.0

alexCaves=5848216
citadel=5633260
farmersDelight=5051242
jei=15.3.0.4
neapolitan=5296594
myNethersDelight=5673085
moonlight=5995640
supplementaries=5948497
zeta=5597406
quark=5594847
upgradeAquatic=5615651
