modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/thelegitdolt/dolt-mod-how/issues"
license = "https://github.com/thelegitdolt/dolt-mod-how/issues"


[[mods]]
modId = "dolt_mod_how"
version = "${file.jarVersion}"
authors = "Dolt"
credits = "Dolt H. Haven"
displayName = "Dolt Mod How"
description = '''
    Hello
    '''

[[dependencies.dolt_mod_how]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.dolt_mod_how]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.dolt_mod_how]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[6.2.0,)"
    ordering = "AFTER"
    side = "BOTH"
